import fs from 'fs';
import { DupGroup } from './types.js';

/**
 * Writes a TypeScript file with type aliases for exact duplicate groups.
 */
export function writeFixFile(groups: DupGroup[], outFile: string) {
  const exact = groups.filter(g => g.similarity === 1);
  let body = `// Auto-generated by dry-lint – identical types unified\n\n`;
  exact.forEach((g, idx) => {
    const baseName = g.decls[0]!.location.name;
    body += `// Group ${idx + 1}\n`;
    // Declare a placeholder for the base type
    body += `export type ${baseName} = {/* replace with real shape */};\n`;
    // Alias remaining duplicates to the base type
    g.decls.slice(1).forEach(d => {
      body += `export type ${d.location.name} = ${baseName};\n`;
    });
    body += `\n`;
  });
  fs.writeFileSync(outFile, body, 'utf8');
}
