name: Docs

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build all packages
        run: bun run build

      - name: Generate Typedoc
        run: |
          bunx typedoc \
            --entryPoints packages/* \
            --entryPointStrategy packages \
            --out docs \
            --exclude '**/*.test.ts' \
            --exclude '**/node_modules/**'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
