name: Publish Packages

permissions:
  contents: write
  id-token: write
  packages: write

on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]

jobs:
  publish:
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.event == 'push' &&
          github.event.workflow_run.head_branch == 'main' &&
          startsWith(github.event.workflow_run.head_commit.message, 'chore: version packages') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache Bun & node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Audit dependencies
        run: |
          if command -v bun &> /dev/null; then
            bun audit --json | tee audit.json
          else
            npm audit --json | tee audit.json
          fi
          jq '.metadata.vulnerabilities.total > 0' audit.json | grep true

      - name: Build packages
        run: bun run build

      - name: Run Test
        run: bun run test

      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish packages
        uses: changesets/action@v1
        with:
          publish: bunx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
